# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Wakatime
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: ${{ secrets.WORKFLOW_TOKEN }}

          # Options
          user: hasanshahriar32
          template: classic
          base: ""
          config_timezone: Asia/Dhaka
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com/@a8a9276c-84b1-4253-addc-95844ce18350
          plugin_wakatime_user: hasanshahriar32
